{
 "title": "Projet Scientifique",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "DATA CAPTEURS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "OK/KO",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"database\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"capteur\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"etat\")"
    }
   ]
  },
  {
   "title": "Intensité",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"database\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"capteur\" and\r\n    r._field == \"intensity\"\r\n  )"
    }
   ]
  },
  { "title": "VALUES CAPTEURS UNIQUE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Capteur 1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "query": "from(bucket: \"database\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"capteur\")\r\n  |> filter(fn: (r) => r[\"numero\"] == \"1\")\r\n\r\n"
    }
   ]
  },
  {
   "title": "Capteur 2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "query": "from(bucket: \"database\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"capteur\")\r\n  |> filter(fn: (r) => r[\"numero\"] == \"2\")\r\n\r\n"
    }
   ]
  },
  {
   "title": "Capteur 3",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "query": "from(bucket: \"database\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"capteur\")\r\n  |> filter(fn: (r) => r[\"numero\"] == \"3\")\r\n\r\n"
    }
   ]
  },
  {
   "title": "Capteur 4",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "query": "from(bucket: \"database\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"capteur\")\r\n  |> filter(fn: (r) => r[\"numero\"] == \"4\")\r\n\r\n"
    }
   ]
  },
  {
   "title": "Capteur 5",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "query": "from(bucket: \"database\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"capteur\")\r\n  |> filter(fn: (r) => r[\"numero\"] == \"5\")\r\n\r\n"
    }
   ]
  },
  {
   "title": "Capteur 6",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "query": "from(bucket: \"database\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"capteur\")\r\n  |> filter(fn: (r) => r[\"numero\"] == \"6\")\r\n\r\n"
    }
   ]
  },
  {
   "title": "Capteur 7",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "query": "from(bucket: \"database\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"capteur\")\r\n  |> filter(fn: (r) => r[\"numero\"] == \"7\")\r\n\r\n"
    }
   ]
  },
  {
   "title": "Capteur 8",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "query": "from(bucket: \"database\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"capteur\")\r\n  |> filter(fn: (r) => r[\"numero\"] == \"8\")\r\n\r\n"
    }
   ]
  },
  {
   "title": "Capteur 9",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "query": "from(bucket: \"database\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"capteur\")\r\n  |> filter(fn: (r) => r[\"numero\"] == \"9\")\r\n\r\n"
    }
   ]
  },
  {
   "title": "Capteur 10",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "query": "from(bucket: \"database\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"capteur\")\r\n  |> filter(fn: (r) => r[\"numero\"] == \"10\")\r\n\r\n"
    }
   ]
  },
  {
   "title": "Capteur 11",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "targets": [
    {
     "query": "from(bucket: \"database\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"capteur\")\r\n  |> filter(fn: (r) => r[\"numero\"] == \"11\")\r\n\r\n"
    }
   ]
  },
  {
   "title": "Capteur 12",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "targets": [
    {
     "query": "from(bucket: \"database\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"capteur\")\r\n  |> filter(fn: (r) => r[\"numero\"] == \"12\")\r\n\r\n"
    }
   ]
  },
  {
   "title": "Capteur 13",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "targets": [
    {
     "query": "from(bucket: \"database\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"capteur\")\r\n  |> filter(fn: (r) => r[\"numero\"] == \"13\")\r\n\r\n"
    }
   ]
  },
  {
   "title": "Capteur 14",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "targets": [
    {
     "query": "from(bucket: \"database\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"capteur\")\r\n  |> filter(fn: (r) => r[\"numero\"] == \"14\")\r\n\r\n"
    }
   ]
  },
  {
   "title": "Capteur 15",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "targets": [
    {
     "query": "from(bucket: \"database\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"capteur\")\r\n  |> filter(fn: (r) => r[\"numero\"] == \"15\")\r\n\r\n"
    }
   ]
  },
  {
   "title": "Capteur 16",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
   "targets": [
    {
     "query": "from(bucket: \"database\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"capteur\")\r\n  |> filter(fn: (r) => r[\"numero\"] == \"16\")\r\n\r\n"
    }
   ]
  },
  {
   "title": "Capteur 17",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
   "targets": [
    {
     "query": "from(bucket: \"database\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"capteur\")\r\n  |> filter(fn: (r) => r[\"numero\"] == \"17\")\r\n\r\n"
    }
   ]
  },
  {
   "title": "Capteur 18",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
   "targets": [
    {
     "query": "from(bucket: \"database\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"capteur\")\r\n  |> filter(fn: (r) => r[\"numero\"] == \"18\")\r\n\r\n"
    }
   ]
  },
  {
   "title": "Capteur 19",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 82 },
   "targets": [
    {
     "query": "from(bucket: \"database\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"capteur\")\r\n  |> filter(fn: (r) => r[\"numero\"] == \"19\")\r\n\r\n"
    }
   ]
  },
  {
   "title": "Capteur 20",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 82 },
   "targets": [
    {
     "query": "from(bucket: \"database\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"capteur\")\r\n  |> filter(fn: (r) => r[\"numero\"] == \"20\")\r\n\r\n"
    }
   ]
  },
  {
   "title": "Capteur 21",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 90 },
   "targets": [
    {
     "query": "from(bucket: \"database\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"capteur\")\r\n  |> filter(fn: (r) => r[\"numero\"] == \"21\")\r\n\r\n"
    }
   ]
  },
  {
   "title": "Capteur 22",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 90 },
   "targets": [
    {
     "query": "from(bucket: \"database\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"capteur\")\r\n  |> filter(fn: (r) => r[\"numero\"] == \"22\")\r\n"
    }
   ]
  },
  {
   "title": "Capteur 23",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 98 },
   "targets": [
    {
     "query": "from(bucket: \"database\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"capteur\")\r\n  |> filter(fn: (r) => r[\"numero\"] == \"23\")\r\n"
    }
   ]
  },
  {
   "title": "Capteur 24",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 98 },
   "targets": [
    {
     "query": "from(bucket: \"database\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"capteur\")\r\n  |> filter(fn: (r) => r[\"numero\"] == \"24\")\r\n"
    }
   ]
  },
  {
   "title": "Capteur 25",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 106 },
   "targets": [
    {
     "query": "from(bucket: \"database\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"capteur\")\r\n  |> filter(fn: (r) => r[\"numero\"] == \"25\")\r\n"
    }
   ]
  },
  {
   "title": "Capteur 26",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 106 },
   "targets": [
    {
     "query": "from(bucket: \"database\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"capteur\")\r\n  |> filter(fn: (r) => r[\"numero\"] == \"26\")\r\n"
    }
   ]
  },
  {
   "title": "Capteur 27",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 114 },
   "targets": [
    {
     "query": "from(bucket: \"database\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"capteur\")\r\n  |> filter(fn: (r) => r[\"numero\"] == \"27\")\r\n"
    }
   ]
  },
  {
   "title": "Capteur 28",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 114 },
   "targets": [
    {
     "query": "from(bucket: \"database\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"capteur\")\r\n  |> filter(fn: (r) => r[\"numero\"] == \"28\")\r\n"
    }
   ]
  },
  {
   "title": "Capteur 29",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 122 },
   "targets": [
    {
     "query": "from(bucket: \"database\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"capteur\")\r\n  |> filter(fn: (r) => r[\"numero\"] == \"29\")\r\n"
    }
   ]
  },
  {
   "title": "Capteur 30",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 122 },
   "targets": [
    {
     "query": "from(bucket: \"database\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"capteur\")\r\n  |> filter(fn: (r) => r[\"numero\"] == \"30\")\r\n"
    }
   ]
  },
  {
   "title": "Capteur 31",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 130 },
   "targets": [
    {
     "query": "from(bucket: \"database\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"capteur\")\r\n  |> filter(fn: (r) => r[\"numero\"] == \"31\")\r\n"
    }
   ]
  },
  {
   "title": "Capteur 32",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 130 },
   "targets": [
    {
     "query": "from(bucket: \"database\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"capteur\")\r\n  |> filter(fn: (r) => r[\"numero\"] == \"32\")\r\n"
    }
   ]
  },
  {
   "title": "Capteur 33",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 138 },
   "targets": [
    {
     "query": "from(bucket: \"database\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"capteur\")\r\n  |> filter(fn: (r) => r[\"numero\"] == \"33\")\r\n"
    }
   ]
  },
  {
   "title": "Capteur 34",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 138 },
   "targets": [
    {
     "query": "from(bucket: \"database\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"capteur\")\r\n  |> filter(fn: (r) => r[\"numero\"] == \"34\")\r\n"
    }
   ]
  },
  {
   "title": "Capteur 35",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 146 },
   "targets": [
    {
     "query": "from(bucket: \"database\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"capteur\")\r\n  |> filter(fn: (r) => r[\"numero\"] == \"35\")\r\n"
    }
   ]
  },
  {
   "title": "Capteur 36",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 146 },
   "targets": [
    {
     "query": "from(bucket: \"database\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"capteur\")\r\n  |> filter(fn: (r) => r[\"numero\"] == \"36\")\r\n"
    }
   ]
  },
  {
   "title": "Capteur 37",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 154 },
   "targets": [
    {
     "query": "from(bucket: \"database\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"capteur\")\r\n  |> filter(fn: (r) => r[\"numero\"] == \"37\")\r\n"
    }
   ]
  },
  {
   "title": "Capteur 38",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 154 },
   "targets": [
    {
     "query": "from(bucket: \"database\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"capteur\")\r\n  |> filter(fn: (r) => r[\"numero\"] == \"38\")\r\n"
    }
   ]
  },
  {
   "title": "Capteur 39",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 162 },
   "targets": [
    {
     "query": "from(bucket: \"database\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"capteur\")\r\n  |> filter(fn: (r) => r[\"numero\"] == \"39\")\r\n"
    }
   ]
  },
  {
   "title": "Capteur 40",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 162 },
   "targets": [
    {
     "query": "from(bucket: \"database\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"capteur\")\r\n  |> filter(fn: (r) => r[\"numero\"] == \"40\")\r\n"
    }
   ]
  },
  {
   "title": "Capteur 41",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 170 },
   "targets": [
    {
     "query": "from(bucket: \"database\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"capteur\")\r\n  |> filter(fn: (r) => r[\"numero\"] == \"41\")"
    }
   ]
  },
  {
   "title": "Capteur 42",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 170 },
   "targets": [
    {
     "query": "from(bucket: \"database\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"capteur\")\r\n  |> filter(fn: (r) => r[\"numero\"] == \"42\")"
    }
   ]
  },
  {
   "title": "Capteur 43",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 178 },
   "targets": [
    {
     "query": "from(bucket: \"database\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"capteur\")\r\n  |> filter(fn: (r) => r[\"numero\"] == \"43\")"
    }
   ]
  },
  {
   "title": "Capteur 44",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 178 },
   "targets": [
    {
     "query": "from(bucket: \"database\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"capteur\")\r\n  |> filter(fn: (r) => r[\"numero\"] == \"44\")"
    }
   ]
  },
  {
   "title": "Capteur 45",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 186 },
   "targets": [
    {
     "query": "from(bucket: \"database\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"capteur\")\r\n  |> filter(fn: (r) => r[\"numero\"] == \"45\")"
    }
   ]
  },
  {
   "title": "Capteur 46",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 186 },
   "targets": [
    {
     "query": "from(bucket: \"database\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"capteur\")\r\n  |> filter(fn: (r) => r[\"numero\"] == \"46\")"
    }
   ]
  },
  {
   "title": "Capteur 47",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 194 },
   "targets": [
    {
     "query": "from(bucket: \"database\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"capteur\")\r\n  |> filter(fn: (r) => r[\"numero\"] == \"47\")"
    }
   ]
  },
  {
   "title": "Capteur 48",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 194 },
   "targets": [
    {
     "query": "from(bucket: \"database\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"capteur\")\r\n  |> filter(fn: (r) => r[\"numero\"] == \"48\")"
    }
   ]
  },
  {
   "title": "Capteur 49",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 202 },
   "targets": [
    {
     "query": "from(bucket: \"database\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"capteur\")\r\n  |> filter(fn: (r) => r[\"numero\"] == \"49\")"
    }
   ]
  },
  {
   "title": "Capteur 50",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 202 },
   "targets": [
    {
     "query": "from(bucket: \"database\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"capteur\")\r\n  |> filter(fn: (r) => r[\"numero\"] == \"50\")"
    }
   ]
  },
  {
   "title": "Capteur 51",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 210 },
   "targets": [
    {
     "query": "from(bucket: \"database\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"capteur\")\r\n  |> filter(fn: (r) => r[\"numero\"] == \"51\")"
    }
   ]
  },
  {
   "title": "Capteur 52",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 210 },
   "targets": [
    {
     "query": "from(bucket: \"database\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"capteur\")\r\n  |> filter(fn: (r) => r[\"numero\"] == \"52\")"
    }
   ]
  },
  {
   "title": "Capteur 53",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 218 },
   "targets": [
    {
     "query": "from(bucket: \"database\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"capteur\")\r\n  |> filter(fn: (r) => r[\"numero\"] == \"53\")"
    }
   ]
  },
  {
   "title": "Capteur 54",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 218 },
   "targets": [
    {
     "query": "from(bucket: \"database\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"capteur\")\r\n  |> filter(fn: (r) => r[\"numero\"] == \"54\")"
    }
   ]
  },
  {
   "title": "Capteur 55",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 226 },
   "targets": [
    {
     "query": "from(bucket: \"database\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"capteur\")\r\n  |> filter(fn: (r) => r[\"numero\"] == \"55\")"
    }
   ]
  },
  {
   "title": "Capteur 56",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 226 },
   "targets": [
    {
     "query": "from(bucket: \"database\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"capteur\")\r\n  |> filter(fn: (r) => r[\"numero\"] == \"56\")"
    }
   ]
  },
  {
   "title": "Capteur 57",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 234 },
   "targets": [
    {
     "query": "from(bucket: \"database\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"capteur\")\r\n  |> filter(fn: (r) => r[\"numero\"] == \"57\")"
    }
   ]
  },
  {
   "title": "Capteur 58",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 234 },
   "targets": [
    {
     "query": "from(bucket: \"database\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"capteur\")\r\n  |> filter(fn: (r) => r[\"numero\"] == \"58\")"
    }
   ]
  },
  {
   "title": "Capteur 59",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 242 },
   "targets": [
    {
     "query": "from(bucket: \"database\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"capteur\")\r\n  |> filter(fn: (r) => r[\"numero\"] == \"59\")"
    }
   ]
  },
  {
   "title": "Capteur 60",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 242 },
   "targets": [
    {
     "query": "from(bucket: \"database\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"capteur\")\r\n  |> filter(fn: (r) => r[\"numero\"] == \"60\")"
    }
   ]
  },
  {
   "title": "Capteur 61",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 250 },
   "targets": [
    {
     "query": "from(bucket: \"database\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"capteur\")\r\n  |> filter(fn: (r) => r[\"numero\"] == \"61\")"
    }
   ]
  },
  {
   "title": "Capteur 62",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 250 },
   "targets": [
    {
     "query": "from(bucket: \"database\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"capteur\")\r\n  |> filter(fn: (r) => r[\"numero\"] == \"62\")"
    }
   ]
  },
  {
   "title": "Capteur 63",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 258 },
   "targets": [
    {
     "query": "from(bucket: \"database\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"capteur\")\r\n  |> filter(fn: (r) => r[\"numero\"] == \"63\")"
    }
   ]
  },
  {
   "title": "Capteur 64",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 258 },
   "targets": [
    {
     "query": "from(bucket: \"database\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"capteur\")\r\n  |> filter(fn: (r) => r[\"numero\"] == \"64\")"
    }
   ]
  },
  {
   "title": "Capteur 65",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 266 },
   "targets": [
    {
     "query": "from(bucket: \"database\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"capteur\")\r\n  |> filter(fn: (r) => r[\"numero\"] == \"65\")"
    }
   ]
  }
 ]
}